### ISSUE TITLE
User Interface Prototype

### ISSUE THREAD

**Issue by KelsieEdie** [ibiyemisi64/SENSE#20]
User interface prototype for the project (10/15)
- Low-fidelity is fine for now
- Try to get it done earlier
- Create prototype for the IQsign registration page and sign creation page.

**Comment by shufanhe** [comment]
Create prototype for the IQsign registration page and sign creation page.

**Comment by KelsieEdie** [comment]
@shufanhe @Xzero864 @ibiyemisi64 Make sure to create a branch off of this issue, so the PR will close the issue

**Comment by Xzero864** [comment]
https://www.figma.com/design/H50qfJ1reTqLfkoMhqTree/SENSE-UI?node-id=0-1&t=070Op1WhPD5TK1Xp-1

Figma Link
